defaults:
  wait: # set default values for "wait" command, these can be overridden below
    cpu: False
    cpu-limit: 30 # percent
    cpu-length: 20 # seconds
    network: True
    network-limit: 1000 # kB/s
    network-length: 90 # seconds
    disk: True
    disk-limit: 5000 # kB/s
    disk-length: 30 # seconds
    time: 10 # seconds, 0=off
    timeout: 0 # seconds, 0=off

recipe:
# these items are handled in sequential order
- wait: 
    cpu: True
    timeout: 180
- launch:
    name: 'Battle.net'
    path: 'C:\Program Files (x86)\Battle.net\Battle.net Launcher.exe'
- wait:
- launch:
    name: 'Epic Games'
    path: 'C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win32\EpicGamesLauncher.exe'
- wait:
- launch:
    name: 'GOG Galaxy'
    path: 'C:\Program Files (x86)\GOG Galaxy\GalaxyClient.exe'
- wait:
- launch:
    name: 'Origin'
    path: 'C:\Program Files (x86)\Origin\Origin.exe'
- wait:
- launch:
    name: 'Steam'
    path: 'C:\Program Files (x86)\Steam\Steam.exe'
- wait:
- launch:
    name: 'Uplay'
    path: 'C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\Uplay.exe'
- wait:
#- launch:
#     name: 'Warframe'
#     path: '%localappdata%\Warframe\Downloaded\Public\Tools\Launcher.exe'
# - wait:
# - launch:
#     name: 'Wargaming.net Game Center'
#     path: 'C:\ProgramData\Wargaming.net\GameCenter\wgc.exe'
# - wait:
